version: '3.1'

services:
  springboot:
    image: 9182709223/spring-boot-mongo:BUILD_NUMBER
    restart: always # This will be ignored if we deploy in docker swarm
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=saisree
    - MONGO_DB_PASSWORD=saisree@123
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - mongo
    networks:
    - springappnetwork 
  mongo:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=saisree
    - MONGO_INITDB_ROOT_PASSWORD=saisree@123
    volumes:
      - mongodb:/data/db
    restart: always
    networks:
    - springappnetwork
    
volumes:
  mongodb:
    driver:local
    
networks:
  springappnetwork:
    driver:bridge
